#!/bin/sh
#
# Activate each Raspberry Pi GPIO pin one after the other.
#
# The purpose of this script is to test pin connections. It is assumed
# that there is some visible (or audible) feedback, such as LED or relay.
# The pins are assumed to have been exported before (see 'exportall').

# The gpio number order used here is a bit peculiar but matches
# the following order of the P1 connector pins:
# - all pins on the left side, in increasing P1 pin number (7, 11, 13, 15).
# - all pins on the right side, in increasing P1 pin number (12, 16, 18, 22).
#
for i in 4 17 27 22 18 23 24 25
do
    echo 0 > /sys/class/gpio/gpio$i/value
    sleep 2
    echo 1 > /sys/class/gpio/gpio$i/value
    sleep 0.5
done

